const QuizTableData = [
    [
        { text: '-' },
        { text: 'Q1' },
        { text: 'Q2' },
        { text: 'Q3' },
        { text: 'Q4' },
        { text: 'Q5' },
        { text: 'Q6' },
    ],
    [
        { text: 'ML' },
        { text: '12OCT' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '20OCT' },
    ],
    [
        { text: 'CG' },
        { text: '-' },
        { text: '15OCT' },
        { text: '19OCT' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
    ],
    [
        { text: 'OS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
    ],
    [
        { text: 'TOA' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
    [
        { text: 'DBS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
    [
        { text: 'PAS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
];

const AssignmentTableData = [
    [
        { text: '-' },
        { text: 'Q1' },
        { text: 'Q2' },
        { text: 'Q3' },
        { text: 'Q4' },
        { text: 'Q5' },
        { text: 'Q6' },
    ],
    [
        { text: 'ML' },
        { text: '12OCT' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '20OCT' },
    ],
    [
        { text: 'CG' },
        { text: '-' },
        { text: '15OCT' },
        { text: '19OCT' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
    ],
    [
        { text: 'OS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
    ],
    [
        { text: 'TOA' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
    [
        { text: 'DBS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
    [
        { text: 'PAS' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '-' },
        { text: '20OCT' },
        { text: '-' },
    ],
];

export { QuizTableData, AssignmentTableData };